#######################
# Theme Customization #
#######################

title: hammer-io         # appears in the header and the HTML <title> tag
author: hammer-io-team   # appears in an HTML <meta> tag, as well as feed.xml
description: >           # appears in an HTML <meta> tag, as well as feed.xml
  DevOps for Javascript-based Microservices
slogan: Hit it with a hammer!        # appears in the header, alongside the title
avatar: /i/Viking_Hammer_Logo_1.png    # appears as portrait in the header
banner: /i/mountains.svg # appears as background in the header
url: http://jekyllrb.com # used by plugins to generate feed.xml and sitemap.xml
baseurl: ''              # prepended to all absolute filepaths
repo: https://github.com/hammer-io/hammer-io.github.io # appears in footer

# Objects listed here will appear in the main nav menu.
# Exceeding four items may cause problems on the desktop (>900px wide) layout.
nav_menu:
  - name: Home
    url: /
    icon: /i/icons.svg#posts # icons should be 24x24 px.
  - name: Status Reports
    url: /reports.html
    icon: /i/icons.svg#posts
  - name: Docs
    url: /documents.html
    icon: /i/icons.svg#posts
  - name: Projects
    url: /projects.html
    icon: /i/icons.svg#portfolio
  - name: GitHub
    url: https://github.com/hammer-io/
    icon: /i/icons.svg#github
    outbound: true      # this key sets a link to open in a new window.
  - name: Team
    url: /team.html
    icon: /i/icons.svg#portfolio


# Objects listed here will appear on the /projects.html page.
projects:
  - title: Tyr
    teaser: A CLI to generate node.js applications in an opinionated way.
    url: https://github.com/hammer-io/tyr
    category: Command Line Interface
  - title: Yggdrasil
    teaser: Connects the nine worlds of microservices.
    url: https://github.com/hammer-io/yggdrasil
    category: Web Application
  - title: Endor
    teaser: The backend web service for Yggdrasil.
    url: https://github.com/hammer-io/endor
    category: Web Application
  - title: Koma
    teaser: Service to accept heartbeat and data information and store it.
    url: https://github.com/hammer-io/koma
    category: Web Application
  - title: Skadi
    teaser: Utility to send heartbeat and data information from express.
    url: https://github.com/hammer-io/skadi
    category: Web Application Module
  - title: Team Website
    teaser: A Jekyll site based on the Solana template.
    url: https://github.com/hammer-io/hammer-io.github.io
    category: Web Application

# Objects listed here will appear on the /documents.html page.
weekly_status_reports:
  - title: Weekly Status Report 1
    teaser: Weekly status report for the week of 9/11 - 9/17
    url: /docs/weekly_status_report_01.pdf
    category: Weekly Status Report 2017
  - title: Weekly Status Report 2
    teaser: Weekly status report for the week of 9/18 - 9/24
    url: /docs/weekly_status_report_02.pdf
    category: Weekly Status Report 2017
  - title: Weekly Status Report 3
    teaser: Weekly status report for the week of 9/25 - 10/01
    url: /docs/weekly_status_report_03.pdf
    category: Weekly Status Report 2017
  - title: Weekly Status Report 4
    teaser: Weekly status report for the week of 10/02 - 10/08
    url: /docs/weekly_status_report_04.pdf
    category: Weekly Status Report 2017
  - title: Weekly Status Report 5
    teaser: Weekly status report for the week of 10/09 - 10/17
    url: /docs/weekly_status_report_05.pdf
    category: Weekly Status Report 2017
  - title: Weekly Status Report 6
    teaser: Weekly status report for the week of 10/18 - 10/24
    url: /docs/weekly_status_report_06.pdf
    category: Weekly Status Report 2017
  - title: Weekly Status Report 7
    teaser: Weekly status report for the week of 10/25 - 10/31
    url: /docs/weekly_status_report_07.pdf
    category: Weekly Status Report 2017
  - title: Weekly Status Report 8
    teaser: Weekly status report for the week of 11/01 - 11/07
    url: /docs/weekly_status_report_08.pdf
    category: Weekly Status Report 2017
  - title: Weekly Status Report 9
    teaser: Weekly status report for the week of 11/08 - 11/14
    url: /docs/weekly_status_report_09.pdf
    category: Weekly Status Report 2017
  - title: Weekly Status Report 10
    teaser: Weekly status report for the weeks of 11/15 - 11/28
    url: /docs/weekly_status_report_10.pdf
    category: Weekly Status Report 2017
  - title: Weekly Status Report 11
    teaser: Weekly status report for the weeks of 11/29 - 12/05
    url: /docs/weekly_status_report_11.pdf
    category: Weekly Status Report 2017
  - title: Biweekly Status Report 12
    teaser: Biweekly status report for the weeks of 01/08 - 01/23
    url: /docs/biweekly_status_report_12.pdf
    category: Weekly Status Report 2018
  - title: Biweekly Status Report 13
    teaser: Biweekly status report for the weeks of 01/24 - 02/06
    url: /docs/biweekly_status_report_13.pdf
    category: Weekly Status Report 2018
  - title: Biweekly Status Report 14
    teaser: Biweekly status report for the weeks of 02/07 - 02/20
    url: /docs/biweekly_status_report_14.pdf
    category: Weekly Status Report 2018
  - title: Biweekly Status Report 15
    teaser: Biweekly status report for the weeks of 02/21 - 03/06
    url: /docs/biweekly_status_report_15.pdf
    category: Weekly Status Report 2018
  - title: Biweekly Status Report 16
    teaser: Biweekly status report for the weeks of 03/07 - 03/20
    url: /docs/biweekly_status_report_16.pdf
    category: Weekly Status Report 2018
  - title: Biweekly Status Report 17
    teaser: Biweekly status report for the weeks of 03/21 - 04/03
    url: /docs/biweekly_status_report_17.pdf
    category: Weekly Status Report 2018

project_plans:
  - title: Project Plan (v1)
    teaser: Outlines the vision and planned direction of the project
    url: /docs/Project_Plan_v1.pdf
    category: Project Plan
    date: 2017-09-24
  - title: Project Plan (v2)
    teaser: Outlines the vision and planned direction of the project
    url: /docs/Project_Plan_v2.pdf
    category: Project Plan
    date: 2017-10-30
  - title: Project Plan (v3)
    teaser: Outlines the vision and planned direction of the project
    url: /docs/Project_Plan_v3.pdf
    category: Project Plan
    date: 2017-12-05
  - title: Design Document (v1)
    teaser: Provides technical details on the software architecture and design
    url: /docs/Design_Document_v1.pdf
    category: Design Document
    date: 2017-10-15
  - title: Design Document (v2)
    teaser: Provides technical details on the software architecture and design
    url: /docs/Design_Document_v2.pdf
    category: Design Document
    date: 2017-12-05
  - title: Presentation 1
    teaser: The slides for the presentation given at the end of SE 491
    url: /docs/powerpoint_presentation_1.pdf
    category: Presentation Slides
    date: 2017-12-05

#################
# Site Settings #
#################

incremental: true
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - TODO.md

permalink: /:collection/:path

collections:
  category: { output: true }
  tag:      { output: true }

defaults:
  - scope:  { type:   posts    }
    values: { layout: post     }
  - scope:  { type:   tag      }
    values: { layout: listing  }
  - scope:  { type:   category }
    values: { layout: listing  }

sass:
  sass_dir: _assets/css

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

paginate: 10
